"use client";

import React, { useState, useEffect, useRef } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Navigation2, ArrowLeft, Locate, Loader2, Edit3, Check, X, GripVertical, Trash2, Search, Send } from 'lucide-react';
import Script from 'next/script';
import { motion, useAnimation, PanInfo, Reorder } from 'framer-motion';
import { GeminiService } from '../services/geminiService';
import { getCourseImage } from '../utils/courseImages';
import LoginInducementModal from '../components/auth/LoginModal';


const aiService = new GeminiService();

// Fix for React 19 / Framer Motion type mismatch
const MotionDiv = motion.div as any;
const ReorderGroup = Reorder.Group as any;
const ReorderItem = Reorder.Item as any;

export const MapView = () => {
  const router = useRouter();
  const searchParams = useSearchParams();

  // --------------------------------------------------------------------------
  // 1. References (Ref) & State 정의
  // --------------------------------------------------------------------------

  // 지도 DOM 및 인스턴스 참조
  const hasAutoGeneratedRef = useRef(false);
  const mapRef = useRef<HTMLDivElement>(null); // 지도가 그려질 DOM 엘리먼트
  const mapInstance = useRef<any>(null);      // Tmap 인스턴스 객체

  // 마커 및 경로 객체 관리 (지도에서 제거/추가를 위해 저장)
  const markersRef = useRef<any[]>([]);       // 현재 표시된 마커들
  const polylinesRef = useRef<any[]>([]);     // 경로(선) 객체들
  const timeMarkersRef = useRef<any[]>([]);   // 시간 표시 마커 관리 (Time Badges)

  // 상세정보 검색 취소용 컨트롤러 (중복 요청 방지 및 취소 처리)
  const abortControllerRef = useRef<AbortController | null>(null);
  const pendingRouteModeRef = useRef<'pedestrian' | 'car' | null>(null); // 코스 전환 시 경로 자동 재계산용

  // UI 상태 관리
  const [activeStep, setActiveStep] = useState(0);    // 코스 모드에서 현재 선택된 단계 (Index)
  const [sheetOpen, setSheetOpen] = useState(true);   // 하단 바텀 시트 열림/닫힘 상태
  const [spots, setSpots] = useState<any[]>([]);      // 여행 코스 데이터 (localStorage에서 로드)

  // 지도 및 로딩 상태
  const [isMapReady, setIsMapReady] = useState(false);      // Tmap 로드 완료 여부
  const [isLoadingRoute, setIsLoadingRoute] = useState(false); // 경로 탐색(도보/차량) 로딩 중 여부

  // 뷰 모드 및 검색 상태
  const [viewMode, setViewMode] = useState<'places' | 'course'>('places'); // 'places'(장소검색) vs 'course'(코스안내)
  const [activeCategory, setActiveCategory] = useState('전체'); // 현재 선택된 장소 카테고리 (맛집, 카페 등)
  const [allPlaces, setAllPlaces] = useState<any[]>([]);    // Tmap API로 검색된 장소 목록

  // 상세 정보 상태
  const [selectedPlace, setSelectedPlace] = useState<{
    name: string;
    content: string;
    img?: string;
    lat?: string | number;
    lng?: string | number;
    address?: string;
    category?: string;
  } | null>(null); // 선택된 장소의 상세 정보
  const [isDetailLoading, setIsDetailLoading] = useState(false); // AI 상세 정보 로딩 중 여부
  const [isSearching, setIsSearching] = useState(false);       // 장소 검색(POI) 로딩 중 여부
  const [isAutoGenerating, setIsAutoGenerating] = useState(false); // 자동 생성 중 여부
  const [autoGenProgress, setAutoGenProgress] = useState<{step: string; message: string; progress: number} | null>(null);

  // 코스 상세 보기 확장 모드 (가로 리스트 vs 상세 스텝 뷰)
  const [isCourseDetailExpanded, setIsCourseDetailExpanded] = useState(false);

  // 기타 UI 상태
  const [isRouteOptionsOpen, setIsRouteOptionsOpen] = useState(false); // 경로 옵션 토글 상태
  const controls = useAnimation(); // Framer Motion 애니메이션 제어

  // 3개 코스 선택 관련 상태
  const [allCourses, setAllCourses] = useState<any[]>([]); // 3개 코스 전체
  const [selectedCourseIndex, setSelectedCourseIndex] = useState(0); // 선택된 코스 인덱스
  const [pickedSpots, setPickedSpots] = useState<any[]>([]); // 사용자가 '담은' 장소들

  // 키워드 검색 상태
  const [searchKeyword, setSearchKeyword] = useState('');

  // [Refine Agent] 코스 수정 채팅 상태
  const [refineInput, setRefineInput] = useState('');
  const [isRefining, setIsRefining] = useState(false);
  const [refineMessage, setRefineMessage] = useState<string | null>(null);
  const [isRefineOpen, setIsRefineOpen] = useState(false);

  // Toast 메시지 상태
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  useEffect(() => {
    if (toastMessage) {
      const timer = setTimeout(() => setToastMessage(null), 3000);
      return () => clearTimeout(timer);
    }
  }, [toastMessage]);

  // [Sync] User Info Sync
  useEffect(() => {
    aiService.syncUser();
  }, []);

  // 편집 모드 상태
  const [isEditMode, setIsEditMode] = useState(false);

  // Guest Login Modal State
  const [showLoginModal, setShowLoginModal] = useState(false);
  const [modalFeature, setModalFeature] = useState("");



  // Helper to check guest status
  const checkIsGuest = () => {
    // If no access token, consider guest
    return !localStorage.getItem('access_token');
  };

  // 줌 제어용 Ref (검색 시 자동 fitBounds 방지)
  const skipFitBoundsRef = useRef(false);

  // Helper: Ensure IDs for spots
  const ensureIds = (places: any[]) => {
    if (!places || !Array.isArray(places)) return [];
    return places.map((p, i) => ({
      ...p,
      id: p.id || `spot-${Date.now()}-${i}`
    }));
  };

  // --------------------------------------------------------------------------
  // 2. Event Listener용 State 참조 (Ref 동기화)
  // Tmap 이벤트 리스너 내부에서 최신 State 값을 참조하기 위해 Ref 사용
  // --------------------------------------------------------------------------
  const activeCategoryRef = useRef(activeCategory);
  useEffect(() => { activeCategoryRef.current = activeCategory; }, [activeCategory]);

  const viewModeRef = useRef(viewMode);
  useEffect(() => { viewModeRef.current = viewMode; }, [viewMode]);

  const sheetOpenRef = useRef(sheetOpen);
  useEffect(() => { sheetOpenRef.current = sheetOpen; }, [sheetOpen]);

  // Tmap POI Search Function
  const searchPlaces = async () => {
    if (!mapInstance.current || !(window as any).Tmapv3) return;

    const Tmapv3 = (window as any).Tmapv3;
    const center = mapInstance.current.getCenter();
    const API_BASE_URL = (process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api").replace(/\/api\/?$/, "");

    // 현재 요청하는 카테고리 캡처
    const targetCategory = activeCategoryRef.current;

    // 검색 키워드 정의
    const keywordMap: { [key: string]: string } = {
      '맛집': '음식점', // "맛집"보다 "음식점"이 더 포괄적이고 정확할 수 있음
      '카페': '카페',
      '관광': '관광명소'
    };

    let keywordsToSearch: string[] = [];
    if (targetCategory === '전체') {
      keywordsToSearch = ['음식점', '카페', '관광명소'];
    } else {
      keywordsToSearch = [keywordMap[targetCategory] || targetCategory];
    }

    try {
      setIsSearching(true); // 로딩 시작

      // 병렬 요청으로 여러 카테고리 동시 검색 (전체일 경우)
      const requests = keywordsToSearch.map(k =>
        fetch(`${API_BASE_URL}/api/tmap/poi/around?keyword=${encodeURIComponent(k)}&lat=${center.lat()}&lng=${center.lng()}&radius=3&count=${targetCategory === '전체' ? 10 : 20}`)
          .then(res => {
            if (!res.ok) throw new Error('Network response was not ok');
            return res.json();
          })
          .then(data => ({ keyword: k, data }))
      );

      const results = await Promise.all(requests);

      // 🚨 중요: 응답을 받았을 때, 사용자가 이미 다른 카테고리를 눌렀다면 이 결과는 버림
      if (activeCategoryRef.current !== targetCategory) {
        console.log(`🚫 [MapView] Ignored old result for ${targetCategory} (Current: ${activeCategoryRef.current})`);
        return;
      }

      let mergedPois: any[] = [];

      results.forEach(({ keyword, data }) => {
        if (data.searchPoiInfo?.pois?.poi) {
          // 키워드를 원래 카테고리명으로 매핑 (UI 표시용)
          let catLabel = targetCategory;
          if (targetCategory === '전체') {
            if (keyword === '음식점') catLabel = '맛집';
            else if (keyword === '카페') catLabel = '카페';
            else if (keyword === '관광명소') catLabel = '관광';
          }

          const pois = data.searchPoiInfo.pois.poi.map((p: any) => ({
            name: p.name,
            lat: p.noorLat,
            lng: p.noorLon,
            category: catLabel,
            address: p.upperAddrName + " " + p.middleAddrName + " " + p.lowerAddrName
          }));
          mergedPois = [...mergedPois, ...pois];
        }
      });

      // 중복 제거 (이름과 좌표가 같은 경우)
      const uniquePois = mergedPois.filter((v, i, a) => a.findIndex(t => (t.name === v.name && t.lat === v.lat)) === i);

      // "주차장" 포함된 장소 필터링
      const filteredPois = uniquePois.filter(p => !p.name.includes("주차장"));

      console.log(`📍 [MapView] Found ${filteredPois.length} places (Category: ${targetCategory})`);

      if (filteredPois.length === 0) {
        console.warn("⚠️ [MapView] No POI found");
      }
      setAllPlaces(filteredPois);

    } catch (err) {
      console.error("❌ [MapView] POI Search Error", err);
    } finally {
      setIsSearching(false); // 로딩 끝
    }
  };

  // Fetch place detail from Agent
  // --------------------------------------------------------------------------
  // 3. AI 상세 정보 조회 (Agent 연동)
  // --------------------------------------------------------------------------
  const fetchPlaceDetail = async (name: string, address: string = "", lat?: number, lng?: number) => {
    // [중복 요청 방지 로직]
    // 1. 이전 요청이 진행 중이라면 취소(abort)시킵니다.
    // 2. 창을 닫거나 다른 마커를 눌렀을 때, 이전 마커의 정보가 늦게 뜨는 것을 방지합니다.
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
    }
    const controller = new AbortController();
    abortControllerRef.current = controller;

    setIsDetailLoading(true);
    setSheetOpen(true); // 상세정보 호출 시 하단 시트 자동 열림

    // allPlaces에서 해당 장소의 상세 정보를 찾습니다 (좌표 등)
    const foundPlace = allPlaces.find(p => p.name === name) || {};

    setSelectedPlace({
      name,
      content: "",
      lat: lat || foundPlace.lat,
      lng: lng || foundPlace.lng,
      address: address || foundPlace.address,
      category: foundPlace.category
    }); // 내용 초기화 및 기본 정보 설정

    try {
      const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";
      // MiniAgent를 사용하는 /api/place-info 엔드포인트 호출
      const response = await fetch(`${API_URL}/place-info`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          place_name: name,
          address: address
        }),
        signal: controller.signal // AbortController Signal 연결
      });

      if (!response.ok) throw new Error('Failed to fetch detail');

      const data = await response.json();

      // 요청이 취소된 상태라면 결과 무시
      if (controller.signal.aborted) return;

      // 상태 업데이트 (UI에 상세 정보 표시)
      setSelectedPlace(prev => ({
        ...prev!, // 기존 lat, lng 유지
        name: data.name || name,
        content: data.content,
        img: data.img
      }));
    } catch (e: any) {
      if (e.name === 'AbortError') {
        console.log("🚫 [MapView] Detail fetch aborted");
        return;
      }
      console.error("❌ [MapView] Detail fetch error", e);
      setSelectedPlace({ name, content: "정보를 불러오는 데 실패했어요." });
    } finally {
      // 현재 완료된 요청이 마지막 요청과 일치할 때만 로딩 종료
      if (abortControllerRef.current === controller) {
        setIsDetailLoading(false);
        abortControllerRef.current = null;
      }
    }
  };

  // --------------------------------------------------------------------------
  // 4. Global Event Handlers for Markers
  // Tmap Marker는 HTML 문자열로 주입되므로, React 함수에 직접 접근할 수 없습니다.
  // 따라서 window 객체에 전역 함수를 할당하여 HTML onclick 이벤트와 연결합니다.
  // --------------------------------------------------------------------------
  useEffect(() => {
    // 마커 아이콘 클릭 시 바로 상세정보를 호출하는 전역 함수
    (window as any).handlePlaceDetail = (name: string, addr: string) => fetchPlaceDetail(name, addr);
  }, [fetchPlaceDetail]);

  // Sheet height constants
  const OPEN_HEIGHT = 540;
  const CLOSED_HEIGHT = 180;

  // Load spots from localStorage or Auto-generate
  useEffect(() => {
    // [FIX] Stale Data Cleanup
    // 이전 버전의(혹은 잘못된) 데이터가 localStorage에 남아있을 경우 강제로 초기화합니다.
    const DATA_VERSION = "v2_fix_photo_mapping";
    const currentVersion = localStorage.getItem("data_version");

    if (currentVersion !== DATA_VERSION) {
      console.warn("🧹 [MapView] Detected stale data version. Clearing localStorage...");
      localStorage.removeItem("all_courses");
      localStorage.removeItem("current_course");
      localStorage.removeItem("spots");
      // 필요하다면 다른 키들도 삭제
      localStorage.setItem("data_version", DATA_VERSION);
    }

    const autoGen = searchParams.get('auto_generate');
    const qUserId = searchParams.get('userId');

    if (qUserId) {
      localStorage.setItem('temp_user_id', qUserId);
    }

    if (autoGen === 'true') {
      // [FIX] React Strict Mode 등에 의한 이중 실행 방지
      if (hasAutoGeneratedRef.current) {
        console.log("🛡️ [MapView] Auto-generation already in progress or done.");
        return;
      }

      // [FIX] 강제 생성 요청(auto_generate=true)이므로, 기존 데이터가 있어도 무시하고 새로 생성합니다.
      // 따라서 기존 데이터가 있다면 초기화하여 충돌을 방지합니다.
      localStorage.removeItem('current_course');
      localStorage.removeItem('all_courses');

      // (기존 스킵 로직 삭제됨)

      // 실행 시작 마킹
      hasAutoGeneratedRef.current = true;

      const runAutoGen = async () => {
        setIsAutoGenerating(true);
        setAutoGenProgress(null);
        try {
          // 채팅에서 넘어온 프롬프트가 있으면 사용, 없으면 기본 메시지
          const customPrompt = searchParams.get('prompt');
          const extraRequest = searchParams.get('extraRequest');
          let agentPrompt = "설문 데이터를 기반으로 바로 코스를 짜줘.";
          if (customPrompt) {
            agentPrompt = decodeURIComponent(customPrompt);
          } else if (extraRequest) {
            agentPrompt = `설문 데이터를 기반으로 코스를 짜줘. 추가 요청: ${decodeURIComponent(extraRequest)}`;
          }

          const response = await aiService.processRequestStream(
            agentPrompt,
            (progress) => setAutoGenProgress(progress)
          );

          // allCourses 처리 (3개 코스)
          if (response.allCourses && response.allCourses.length > 0) {
            const allCoursesForMap = response.allCourses.map((course: any) => ({
              course_id: course.course_id,
              course_name: course.course_name,
              course_description: course.course_description || '',
              places: (course.cards && Array.isArray(course.cards)) ? course.cards.map((c: any, i: number) => ({
                id: c.placeId || i.toString(),
                type: '놀거리',
                name: c.name || c.placeId,
                lat: c.lat || 0,
                lng: c.lng || 0,
                desc: c.reason,
                tags: c.keywords || [],
                transport: '이동',
                img: c.img
              })) : []
            }));
            setAllCourses(allCoursesForMap);
            localStorage.setItem('all_courses', JSON.stringify(allCoursesForMap));

            // 첫 번째 코스로 설정
            if (allCoursesForMap[0]?.places) {
              setSpots(ensureIds(allCoursesForMap[0].places));
              setSelectedCourseIndex(0);
            }
            setViewMode('course');
            console.log("✅ [MapView] Auto-generated 3 courses loaded");
          } else if (response.evidenceCards && response.evidenceCards.length > 0) {
            // fallback: evidenceCards만 있는 경우
            const safeSpots = ensureIds(response.evidenceCards);
            setSpots(safeSpots);
            localStorage.setItem('current_course', JSON.stringify(safeSpots));
            setViewMode('course');
            console.log("✅ [MapView] Auto-generated course loaded");
          } else {
            // 코스가 없는 경우 (유효하지 않은 입력 등) → 채팅으로 되돌아가기
            const responseMsg = response.text || "입력을 다시 확인해주세요.";
            console.warn("⚠️ [MapView] No courses returned, redirecting to chat:", responseMsg);
            setToastMessage(responseMsg);
            setTimeout(() => {
              router.push(`/chat?mode=course_init&invalidMsg=${encodeURIComponent(responseMsg)}`);
            }, 1500);
          }
        } catch (e) {
          console.error("❌ [MapView] Auto-generation failed", e);
          setToastMessage("코스 생성 중 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.");
        } finally {
          setIsAutoGenerating(false);
          setAutoGenProgress(null);
          // 성공 시 토스트 및 URL 정리
          if (localStorage.getItem('all_courses') || localStorage.getItem('current_course')) {
            setToastMessage("코스가 생성되었습니다!");

            const params = new URLSearchParams(searchParams.toString());
            params.delete('auto_generate');
            params.delete('prompt');
            params.delete('extraRequest');
            router.replace(`/map?${params.toString()}`);
          }
        }
      };
      runAutoGen();
    } else {
      try {
        // 3개 코스 전체 로드
        const storedAllCourses = localStorage.getItem('all_courses');
        if (storedAllCourses) {
          const parsedAllCourses = JSON.parse(storedAllCourses);

          // [Fix] 이미지 복구: img가 없거나 localhost URL이면 getCourseImage로 복구
          const isLocal = window.location.hostname === 'localhost';
          const restoredCourses = parsedAllCourses.map((course: any) => ({
            ...course,
            places: (course.places || []).map((p: any) => {
              let imgUrl = p.img;
              // localhost URL이 Cloud Run에서 무효화되는 문제 수정
              if (imgUrl && imgUrl.includes('localhost') && !isLocal) {
                imgUrl = null;
              }
              // photo_name이 있으면 현재 도메인 기준 URL 재구성
              if (!imgUrl && p.photo_name) {
                const baseUrl = (process.env.NEXT_PUBLIC_API_URL || '').replace(/\/api\/?$/, '');
                imgUrl = `${baseUrl}/api/photo?name=${p.photo_name}`;
              }
              return {
                ...p,
                img: imgUrl || getCourseImage([p.type || '장소'], p.name || '')
              };
            })
          }));

          setAllCourses(restoredCourses);

          // 첫 번째 코스를 기본으로 설정
          if (restoredCourses.length > 0 && restoredCourses[0].places) {
            setSpots(ensureIds(restoredCourses[0].places));
            setSelectedCourseIndex(0);
            setViewMode('course');
            console.log("✅ [MapView] Loaded all 3 courses, displaying course 1");

            // pickedSpots는 사용자가 "담기" 버튼으로 직접 고른 장소만 담는 세션 상태이므로 복원하지 않음
          }
        } else {
          // fallback: 기존 current_course 로드
          const stored = localStorage.getItem('current_course');
          if (stored) {
            const parsed = JSON.parse(stored);
            setSpots(ensureIds(parsed));
            setViewMode('course');
          } else {
            setViewMode('places');
          }
        }
      } catch (e) {
        console.error("❌ [MapView] Failed to load data", e);
      }
    }
  }, [searchParams]);


  // --------------------------------------------------------------------------
  // 5. Tmap 초기화 (최초 1회 실행)
  // --------------------------------------------------------------------------
  const initMap = () => {
    console.log("🗺️ [MapView] initMap called");
    if (typeof window === 'undefined' || !(window as any).Tmapv3) {
      console.error("❌ [MapView] Tmapv3 not loaded");
      return;
    }

    if (mapInstance.current) {
      console.log("ℹ️ [MapView] Map instance already exists");
      return;
    }

    const Tmapv3 = (window as any).Tmapv3;

    // [초기 중심 좌표 설정]
    // 첫 번째 장소 위치로 설정하거나, 데이터가 없으면 광주 시청 좌표를 기본값으로 사용
    let initialLat = 35.1595;
    let initialLng = 126.8526;

    const storedCourse = localStorage.getItem('current_course');
    if (storedCourse) {
      try {
        const parsed = JSON.parse(storedCourse);
        if (parsed.length > 0 && parsed[0].lat && parsed[0].lng) {
          initialLat = parseFloat(parsed[0].lat);
          initialLng = parseFloat(parsed[0].lng);
          console.log("📍 [MapView] Using first spot as initial center:", initialLat, initialLng);
        }
      } catch (e) { /* ignore */ }
    }

    // [지도 객체 생성]
    mapInstance.current = new Tmapv3.Map(mapRef.current, {
      center: new Tmapv3.LatLng(initialLat, initialLng),
      width: "100%",
      height: "100%",
      zoom: 15, // 초기 줌 레벨 (조금 더 확대)
      zoomControl: false, // 줌 컨트롤 숨김 (깔끔한 UI)
    });

    console.log("✅ [MapView] Map instance created");
    setIsMapReady(true);

    // [지도 빈 공간 클릭 이벤트 핸들러]
    // 지도 배경을 클릭했을 때, 활성화된 UI 요소들을 닫는 역할
    mapInstance.current.on("Click", async (evt: any) => {
      // Reverse Geocoding 제거됨: 단순히 선택 해제 및 시트 닫기 처리
      console.log(`🖱️ [MapView] Map Clicked (Reverse Geo Disabled)`);

      // 선택된 장소가 있다면 해제
      setSelectedPlace(null);
      setIsDetailLoading(false);

      // 코스 모드일 때 시트 닫기
      if (viewModeRef.current === 'course' && sheetOpenRef.current) {
        setSheetOpen(false);
      }
    });

  };

  // Render initial markers and adjust bounds
  useEffect(() => {
    if (isMapReady && mapInstance.current && (window as any).Tmapv3) {
      const Tmapv3 = (window as any).Tmapv3;

      // Clear existing
      markersRef.current.forEach(m => m.setMap(null));
      markersRef.current = [];
      polylinesRef.current.forEach(p => p.setMap(null));
      polylinesRef.current = [];

      const bounds = new Tmapv3.LatLngBounds();
      const path: any[] = [];

      // 표시할 데이터 결정 (코스 모드 vs 주변 장소 모드)
      // 장소 모드일 때는 allPlaces(검색 결과)를 사용
      const displayData = viewMode === 'course' ? spots : allPlaces;

      displayData.forEach((spot, index) => {
        const lat = parseFloat(spot.lat);
        const lng = parseFloat(spot.lng);
        if (isNaN(lat) || isNaN(lng)) return;

        const position = new Tmapv3.LatLng(lat, lng);
        path.push(position);
        bounds.extend(position);

        let markerIcon = "📍";
        let markerBg = "white";
        let markerBorder = "#0066FF";

        if (viewMode === 'places') {
          if (spot.category === '맛집') {
            markerIcon = "🍴";
            markerBg = "#FFF0F0";
            markerBorder = "#FF4444";
          } else if (spot.category === '카페') {
            markerIcon = "☕";
            markerBg = "#F0F5FF";
            markerBorder = "#4488FF";
          } else if (spot.category === '관광') {
            markerIcon = "🎡";
            markerBg = "#F0FFF4";
            markerBorder = "#00C853";
          }
        }

        const markerContent = viewMode === 'course'
          ? `<div style="background:#0066FF; color:white; padding:4px 10px; border-radius:20px; font-weight:900; font-size:12px; border:2px solid white; box-shadow: 0 4px 12px rgba(0,0,0,0.1); cursor: pointer; pointer-events: auto;">${index + 1}</div>`
          : `<div style="display:flex; flex-direction:column; align-items:center; pointer-events:none;">
               <div onclick="window.handlePlaceDetail('${spot.name.replace(/'/g, "\\'")}', '${(spot.address || "").replace(/'/g, "\\'")}'); event.stopPropagation();"
                    style="background:${markerBg}; color:${markerBorder}; padding:6px; border-radius:50%; width:32px; height:32px; display:flex; align-items:center; justify-content:center; border:2px solid ${markerBorder}; box-shadow: 0 4px 12px rgba(0,0,0,0.1); font-size:16px; cursor: pointer; pointer-events: auto;">${markerIcon}</div>
               <span style="background:white; margin-top:4px; padding:3px 8px; border-radius:8px; border:1px solid #eee; font-size:11px; font-weight:bold; color:#333; box-shadow:0 2px 4px rgba(0,0,0,0.05); white-space:nowrap; max-width:120px; overflow:hidden; text-overflow:ellipsis; pointer-events:none;">${spot.name}</span>
             </div>`;

        const markerOptions: any = {
          position: position,
          map: mapInstance.current,
          iconHTML: markerContent,
        };

        // 장소 모드: 아이콘 중앙(16px)에 앵커 포인트 설정하여 위치 고정
        if (viewMode === 'places' && Tmapv3.Point) {
          markerOptions.offset = new Tmapv3.Point(16, 16);
        }

        const marker = new Tmapv3.Marker(markerOptions);

        // Marker Click Event
        const onMarkerClick = () => {
          if (viewMode === 'course') {
            // 코스 모드일 때는 해당 단계의 카드를 보여줌 (AI 검색 X)
            setActiveStep(index);
            setSelectedPlace(null);
            setSheetOpen(true);
          }
          // 장소 모드일 때는 마커 클릭 시 아무 동작 안함 (버튼 클릭으로 처리)
        };

        if (marker.on) {
          marker.on("Click", onMarkerClick);
          marker.on("click", onMarkerClick);
        } else if (marker.addListener) {
          marker.addListener("click", onMarkerClick);
        }

        markersRef.current.push(marker);
      });

      if (viewMode === 'course' && displayData.length > 1) {
        const polyline = new Tmapv3.Polyline({
          path: path,
          strokeColor: "#0066FF",
          strokeWeight: 4,
          strokeOpacity: 0.5,
          map: mapInstance.current,
          strokeStyle: "dashed"
        });
        polylinesRef.current.push(polyline);
      }

      if (displayData.length > 0) {
        // 검색으로 인한 수동 이동 시 fitBounds 건너뛰기
        if (skipFitBoundsRef.current) {
          skipFitBoundsRef.current = false;
          return;
        }

        // 마커 렌더링 후 지도 범위 재설정
        // 지도가 렌더링된 직후 fitBounds를 호출하여 전체 마커가 보이도록 조정
        setTimeout(() => {
          if (mapInstance.current) {
            // 하단 바텀 시트가 지도를 가리는 것을 고려하여 Padding(Margin) 적용
            // viewMode가 'course'일 때는 시트가 높게 올라오므로 하단 여백을 크게 설정
            const bottomPadding = viewMode === 'course' ? 320 : 150;

            // Tmapv3 fitBounds(bounds, margin) 사용
            // margin: { top, right, bottom, left }
            mapInstance.current.fitBounds(bounds, {
              top: 80,
              bottom: bottomPadding,
              left: 40,
              right: 40
            });
          }
        }, 150);
      }
    }
  }, [spots, allPlaces, viewMode, activeCategory, isMapReady]);

  // Route mode state: 'pedestrian' or 'car'
  const [routeMode, setRouteMode] = useState<'pedestrian' | 'car'>('pedestrian');
  const [totalTime, setTotalTime] = useState<number>(0); // 초 단위
  const [totalFare, setTotalFare] = useState<number>(0); // 택시 요금
  const [segmentTimes, setSegmentTimes] = useState<number[]>([]); // 각 구간별 소요 시간
  const [segmentInfos, setSegmentInfos] = useState<any[]>([]); // 구간별 상세 정보 (좌표 포함)

  // [MODIFIED] Auto-calculate removed to allow manual trigger only

  // Render Time Badges on Map
  useEffect(() => {
    if (!mapInstance.current || !(window as any).Tmapv3) return;
    const Tmapv3 = (window as any).Tmapv3;

    // Clear existing time markers
    timeMarkersRef.current.forEach(m => m.setMap(null));
    timeMarkersRef.current = [];

    if (viewMode === 'course' && segmentInfos.length > 0) {
      const isCar = routeMode === 'car';
      const bgColor = isCar ? '#1F2937' : '#FFFFFF';
      const borderColor = isCar ? '#F59E0B' : '#0066FF'; // Amber for taxi, Blue for walk
      const textColor = isCar ? '#FCD34D' : '#0066FF';
      const iconSymbol = isCar ? '🚖' : '🚶';
      const shadowRing = isCar ? 'rgba(245, 158, 11, 0.3)' : 'rgba(0,102,255,0.1)';

      segmentInfos.forEach(info => {
        if (info.time <= 0) return;
        const position = new Tmapv3.LatLng(info.lat, info.lng);
        const timeStr = formatTime(info.time);

        const content = `
                <div style="
                    background: ${bgColor};
                    padding: 6px 12px;
                    border-radius: 24px;
                    box-shadow: 0 4px 10px rgba(0,0,0,0.3), 0 0 0 2px ${shadowRing};
                    border: 2px solid ${borderColor};
                    display: flex;
                    align-items: center;
                    gap: 5px;
                    transform: translate(-50%, -50%);
                    white-space: nowrap;
                    pointer-events: none;
                    z-index: 100;
                ">
                    <span style="font-size: 14px;">${iconSymbol}</span>
                    <span style="font-size: 12px; font-weight: 900; color: ${textColor}; letter-spacing: -0.5px;">${timeStr}</span>
                </div>
            `;

        const marker = new Tmapv3.Marker({
          position: position,
          map: mapInstance.current,
          iconHTML: content,
          zIndex: 100
        });
        timeMarkersRef.current.push(marker);
      });
    }
  }, [segmentInfos, viewMode, isMapReady, routeMode]);

  // Fetch and draw route based on mode
  const fetchRoute = React.useCallback(async (mode: 'pedestrian' | 'car') => {
    if (!isMapReady || spots.length < 2) return;
    setIsLoadingRoute(true);
    setRouteMode(mode);

    const Tmapv3 = (window as any).Tmapv3;
    const APP_KEY = process.env.NEXT_PUBLIC_TMAP_APP_KEY || "";

    try {
      // Clear existing routes
      polylinesRef.current.forEach(p => p.setMap(null));
      polylinesRef.current = [];

      let accumulatedTime = 0;
      let accumulatedFare = 0;
      const collectedSegments: any[] = [];
      const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";
      const routeEndpoint = mode === 'pedestrian'
        ? `${API_BASE_URL}/tmap/routes/pedestrian`
        : `${API_BASE_URL}/tmap/routes`;

      for (let i = 0; i < spots.length - 1; i++) {
        const start = spots[i];
        const end = spots[i + 1];

        const response = await fetch(routeEndpoint, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            startX: String(start.lng),
            startY: String(start.lat),
            endX: String(end.lng),
            endY: String(end.lat),
            reqCoordType: "WGS84GEO",
            resCoordType: "WGS84GEO",
            startName: encodeURIComponent(start.name),
            endName: encodeURIComponent(end.name)
          })
        });

        const data = await response.json();

        if (data.features) {
          // Segment Time Logic
          let segmentTime = 0;

          if (mode === 'car' && data.features.length > 0) {
            const props = data.features[0].properties;
            if (props && props.taxiFare) {
              accumulatedFare += props.taxiFare;
            }
          }

          const linePath: any[] = [];
          data.features.forEach((feature: any) => {
            if (feature.properties?.totalTime) {
              accumulatedTime += feature.properties.totalTime;
              segmentTime += feature.properties.totalTime;
            }
            if (feature.geometry.type === "LineString") {
              feature.geometry.coordinates.forEach((coord: any) => {
                linePath.push(new Tmapv3.LatLng(coord[1], coord[0]));
              });
            }
          });

          // Collect Segment Info
          collectedSegments.push({
            lat: (parseFloat(start.lat) + parseFloat(end.lat)) / 2,
            lng: (parseFloat(start.lng) + parseFloat(end.lng)) / 2,
            time: segmentTime
          });

          // 경로 색상: 도보=파랑, 차량=초록
          const routeColor = mode === 'pedestrian' ? "#0066FF" : "#00C853";
          const routePolyline = new Tmapv3.Polyline({
            path: linePath,
            strokeColor: routeColor,
            strokeWeight: 6,
            map: mapInstance.current
          });
          polylinesRef.current.push(routePolyline);
        }
      }

      setSegmentInfos(collectedSegments);
      setTotalTime(accumulatedTime);
      console.log(`✅ ${mode} route loaded. Total time: ${Math.round(accumulatedTime / 60)} min`);

    } catch (error) {
      console.error("Route fetch failed", error);
      alert("경로를 불러오는데 실패했습니다.");
    } finally {
      setIsLoadingRoute(false);
    }
  }, [isMapReady, spots]);

  // [MODIFIED] Auto-update removed. Route updates only on button click.

  // 장소 탭 진입 시 자동 검색 (최초 진입 또는 탭 전환 시)
  // 코스 자동생성 중에는 불필요한 장소 검색을 실행하지 않음
  useEffect(() => {
    if (isMapReady && viewMode === 'places' && allPlaces.length === 0 && !isAutoGenerating) {
      searchPlaces();
    }
  }, [isMapReady, viewMode, isAutoGenerating]);

  // Helper: format seconds to "X분"
  const formatTime = (seconds: number) => {
    const mins = Math.round(seconds / 60);
    if (mins < 60) return `${mins}분`;
    const hours = Math.floor(mins / 60);
    const remainMins = mins % 60;
    return `${hours}시간 ${remainMins}분`;
  };


  // Active step change -> move map center
  useEffect(() => {
    if (mapInstance.current && (window as any).Tmapv3 && spots[activeStep]) {
      const Tmapv3 = (window as any).Tmapv3;
      const pos = new Tmapv3.LatLng(spots[activeStep].lat, spots[activeStep].lng);
      mapInstance.current.panTo(pos);
    }
  }, [activeStep, spots]);

  const nextStep = () => setActiveStep(prev => (prev < spots.length - 1 ? prev + 1 : prev));
  const prevStep = () => setActiveStep(prev => (prev > 0 ? prev - 1 : prev));

  // Handle Drag End to snap to Open or Closed
  const handleDragEnd = (_: any, info: PanInfo) => {
    const shouldClose = info.velocity.y > 20 || info.offset.y > 100;
    const shouldOpen = info.velocity.y < -20 || info.offset.y < -100;

    if (shouldClose) {
      setSheetOpen(false);
      // 시트를 내려도 상세정보(selectedPlace)는 유지 — 다시 올리면 그대로 표시
    } else if (shouldOpen) {
      setSheetOpen(true);
    }
  };

  // Sync sheetOpen state with animation
  useEffect(() => {
    controls.start({
      height: sheetOpen ? OPEN_HEIGHT : CLOSED_HEIGHT,
      transition: { type: 'spring', damping: 25, stiffness: 200 }
    });
  }, [sheetOpen, controls]);

  // Tmap 로드 감지 및 초기화 (Safety Check)
  useEffect(() => {
    const checkTmap = setInterval(() => {
      if ((window as any).Tmapv3 && !mapInstance.current) {
        console.log("🔄 [MapView] Tmapv3 detected via interval, initializing...");
        initMap();
        clearInterval(checkTmap);
      }
    }, 1000); // 1초마다 체크
    return () => clearInterval(checkTmap);
  }, []);

  // 코스 선택 핸들러
  const handleCourseSelect = (index: number) => {
    if (allCourses[index] && allCourses[index].places) {
      // 경로가 활성 상태였으면 코스 전환 후 자동 재계산 예약
      if (totalTime > 0 || segmentInfos.length > 0) {
        pendingRouteModeRef.current = routeMode;
      }

      setSelectedCourseIndex(index);
      setSpots(ensureIds(allCourses[index].places));
      setActiveStep(0);
      setIsEditMode(false);

      // Reset Route Data (spots 업데이트 후 useEffect에서 재계산됨)
      setTotalTime(0);
      setTotalFare(0);
      setSegmentTimes([]);
      setSegmentInfos([]);

      console.log(`📍 [MapView] Switched to course ${index + 1}: ${allCourses[index].course_name}`);
    }
  };

  // 코스 전환 후 경로 자동 재계산
  useEffect(() => {
    if (pendingRouteModeRef.current && spots.length >= 2 && isMapReady) {
      const mode = pendingRouteModeRef.current;
      pendingRouteModeRef.current = null;
      fetchRoute(mode);
    }
  }, [spots, isMapReady, fetchRoute]);

  // [Refine Agent] 코스 수정 요청 핸들러
  const handleRefine = async () => {
    if (!refineInput.trim() || isRefining) return;
    const msg = refineInput.trim();
    setRefineInput('');
    setIsRefining(true);
    setRefineMessage(null);

    try {
      const result = await aiService.refineCourse(msg, selectedCourseIndex);

      if (result.success && result.courses) {
        // 수정된 코스에 이미지 보존 (img가 없으면 기존 이미지 또는 getCourseImage 사용)
        const mergedCourses = result.courses.map((course: any, ci: number) => ({
          ...course,
          places: (course.places || []).map((p: any, pi: number) => {
            // 기존 코스에서 같은 위치의 이미지 가져오기 (변경 안 된 장소)
            const oldPlace = allCourses[ci]?.places?.[pi];
            return {
              ...p,
              img: p.img || oldPlace?.img || getCourseImage([p.type || '장소'], p.name),
            };
          })
        }));

        setAllCourses(mergedCourses);
        localStorage.setItem('all_courses', JSON.stringify(mergedCourses));

        // 현재 코스 업데이트
        if (mergedCourses[selectedCourseIndex]?.places) {
          setSpots(ensureIds(mergedCourses[selectedCourseIndex].places));
        }

        setRefineMessage(result.changeSummary || result.message);
        setToastMessage(result.changeSummary || '코스가 수정되었어요!');
      } else {
        setRefineMessage(result.message);
      }
    } catch (e) {
      setRefineMessage('수정 중 오류가 발생했어요.');
    } finally {
      setIsRefining(false);
      // 3초 후 메시지 숨기기
      setTimeout(() => setRefineMessage(null), 5000);
    }
  };

  // 장소 담기/빼기 토글 핸들러
  const togglePickSpot = (e: React.MouseEvent, spot: any) => {
    e.stopPropagation(); // 카드 클릭 이벤트 방지

    // [Guest Check]
    if (checkIsGuest()) {
      setModalFeature("장소 담기");
      setShowLoginModal(true);
      return;
    }

    // 이미 담겼는지 확인
    const isPicked = pickedSpots.some(p => p.name === spot.name && p.lat === spot.lat);

    if (isPicked) {
      // 이미 담겼으면 제거
      setPickedSpots(prev => prev.filter(p => !(p.name === spot.name && p.lat === spot.lat)));
    } else {
      // 안 담겼으면 추가
      setPickedSpots(prev => [...prev, spot]);
    }
  };

  // 코스 확정 및 타임라인 생성 핸들러
  const handleConfirmCourse = async () => {
    // [Guest Check]
    if (checkIsGuest()) {
      setModalFeature("코스 확정 및 저장");
      setShowLoginModal(true);
      return;
    }

    // 1. 코스 결정 (Custom Mix vs Single Selection)
    let finalSpots: any[] = [];
    let isCustomMix = false;

    if (pickedSpots.length > 0) {
      // [Case A] 사용자가 장소를 직접 담은 경우 (Mix & Match)
      if (confirm(`담아두신 ${pickedSpots.length}개의 장소로 '나만의 코스'를 확정하시겠습니까?`)) {
        finalSpots = pickedSpots;
        isCustomMix = true;
      } else {
        return; // 취소
      }
    } else {
      // [Case B] 현재 보고 있는 추천 코스 그대로 선택
      if (spots.length === 0) {
        alert("코스에 장소가 없습니다.");
        return;
      }
      finalSpots = spots;
    }

    // 2. Backend DB 저장 (History Archiving)
    try {
      const userId = localStorage.getItem('temp_user_id');
      if (userId) {
        const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api';

        const selectedMeta = allCourses[selectedCourseIndex] || {};
        const summary = selectedMeta.ai_summary || selectedMeta.course_name || "나만의 광주 여행";

        // [MODIFIED] Send all courses + Custom Mix info
        await fetch(`${API_URL}/journey/save-final`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            userId: userId,
            selectedCourseIndex: isCustomMix ? -1 : selectedCourseIndex,
            customPlaces: isCustomMix ? finalSpots : null,
            allCourses: allCourses,
            aiSummary: summary
          })
        });
        console.log("✅ Courses saved to DB history (CustomMix:", isCustomMix, ")");
      }
    } catch (error) {
      console.error("❌ Failed to save courses to DB:", error);
    }

    // 3. 지도 상태 정리 (확정된 코스만 남기기)
    let newSingleCourseList;

    if (isCustomMix) {
      newSingleCourseList = [{
        course_id: `custom-${Date.now()}`,
        course_name: `나만의 커스텀 여행 (${new Date().getMonth() + 1}/${new Date().getDate()})`,
        description: "직접 선택한 장소들로 구성된 코스",
        places: finalSpots,
        cards: [],
        is_selected: true // [Mod] Local state update
      }];
    } else {
      const confirmedMeta = allCourses[selectedCourseIndex];
      newSingleCourseList = [{
        ...confirmedMeta,
        places: finalSpots,
        is_selected: true // [Mod] Local state update
      }];
    }

    setAllCourses(newSingleCourseList);
    setSpots(finalSpots);
    setSelectedCourseIndex(0);
    setPickedSpots([]); // 장바구니 비우기

    localStorage.setItem('all_courses', JSON.stringify(newSingleCourseList));
    localStorage.setItem('current_course', JSON.stringify(finalSpots));
    localStorage.setItem('current_course_meta', JSON.stringify(newSingleCourseList[0]));

    // 4. 이전 여행 상태 초기화 후 여행 모드 페이지로 이동
    localStorage.removeItem('travel_visited_steps');
    router.push('/travel');
  };

  // 순서 변경 핸들러 (Reorder)
  const handleReorder = (newSpots: any[]) => {
    setSpots(newSpots);

    // 로컬 스토리지 업데이트
    const updatedAllCourses = [...allCourses];
    if (updatedAllCourses[selectedCourseIndex]) {
      updatedAllCourses[selectedCourseIndex].places = newSpots;
      setAllCourses(updatedAllCourses);
      localStorage.setItem('all_courses', JSON.stringify(updatedAllCourses));
    }
    localStorage.setItem('current_course', JSON.stringify(newSpots));
  };

  // 장소 삭제 핸들러
  const handleDeleteSpot = (indexToRemove: number, e: React.MouseEvent) => {
    e.stopPropagation();
    if (confirm("이 장소를 코스에서 삭제하시겠습니까?")) {
      const newSpots = spots.filter((_, index) => index !== indexToRemove);
      handleReorder(newSpots); // Use handleReorder to save changes
    }
  };

  // 장소 코스 추가 핸들러
  const addToCourse = () => {
    if (!selectedPlace) return;

    // 중복 추가 방지
    const exists = spots.some(s => s.name === selectedPlace.name);
    if (exists) {
      setToastMessage("이미 코스에 추가된 장소입니다.");
      return;
    }

    const newSpot = {
      id: `spot-${Date.now()}`,
      type: selectedPlace.category || '놀거리',
      name: selectedPlace.name,
      lat: selectedPlace.lat || 0,
      lng: selectedPlace.lng || 0,
      desc: selectedPlace.content,
      tags: [],
      transport: '이동',
      img: selectedPlace.img,
      address: selectedPlace.address,
      category: selectedPlace.category || '장소'
    };

    const newSpots = [...spots, newSpot];
    // 추가 시에는 현재 지도 뷰 유지 (fitBounds 방지)
    skipFitBoundsRef.current = true;
    handleReorder(newSpots);
    setToastMessage(`'${selectedPlace.name}'이(가) 코스에 추가되었습니다.`);
  };

  // 키워드 검색 핸들러
  const handleKeywordSearch = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!searchKeyword.trim()) return;

    setIsSearching(true);
    setViewMode('places'); // 결과 확인을 위해 장소 모드로 전환

    // 키보드 내리기 (모바일 고려)
    if (document.activeElement instanceof HTMLElement) {
      document.activeElement.blur();
    }

    try {
      const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";
      const response = await fetch(`${API_URL}/tmap/poi/search?keyword=${encodeURIComponent(searchKeyword)}`);
      if (!response.ok) throw new Error('Search failed');

      const data = await response.json();

      if (data.searchPoiInfo?.pois?.poi) {
        const pois = data.searchPoiInfo.pois.poi.map((p: any) => ({
          name: p.name,
          lat: p.noorLat,
          lng: p.noorLon,
          category: p.lowerAddrName || '장소',
          address: (p.upperAddrName + " " + p.middleAddrName + " " + p.lowerAddrName).trim()
        }));

        // 줌 제어 Ref 설정 (useEffect의 fitBounds 방지)
        skipFitBoundsRef.current = true;
        setAllPlaces(pois);
        setToastMessage(`'${searchKeyword}' 검색 완료: ${pois.length}개 발견`);

        // 첫 번째 결과로 지도 이동
        if (pois.length > 0 && mapInstance.current && (window as any).Tmapv3) {
          const Tmapv3 = (window as any).Tmapv3;
          mapInstance.current.setCenter(new Tmapv3.LatLng(pois[0].lat, pois[0].lng));
          mapInstance.current.setZoom(15);
        }
      } else {
        setAllPlaces([]);
        setToastMessage("검색 결과가 없습니다.");
      }
    } catch (error) {
      console.error("Search failed", error);
      setToastMessage("검색 중 오류가 발생했습니다.");
    } finally {
      setIsSearching(false);
    }
  };

  return (
    <div className="h-screen bg-gray-50 relative overflow-hidden font-['Inter']">

      {/* Toast Notification */}
      {toastMessage && (
        <div className="fixed top-24 left-1/2 -translate-x-1/2 z-[9999] animate-fade-in-down">
          <div className="bg-gray-900/90 backdrop-blur-md text-white px-6 py-3 rounded-full shadow-2xl flex items-center gap-3 border border-white/10">
            <Check size={18} className="text-[#00C853]" />
            <span className="text-sm font-bold">{toastMessage}</span>
          </div>
        </div>
      )}

      {/* Global Loading Overlay for Auto-Generation (SSE Progress) */}
      {isAutoGenerating && (
        <div className="fixed inset-0 z-[1000] bg-white/90 backdrop-blur-xl flex flex-col items-center justify-center px-8 animate-fade-in">
          {/* 마스코트 + 스피너 */}
          <div className="relative mb-8">
            <div className="w-28 h-28 rounded-full bg-white shadow-xl border-2 border-blue-100 overflow-hidden">
              <img src="/mascot_circle.png" alt="AI" className="w-full h-full object-cover" />
            </div>
            <div className="absolute -inset-2 rounded-full border-[3px] border-transparent border-t-[#0066FF] animate-spin" />
          </div>

          {/* 제목 */}
          <h2 className="text-xl font-black text-gray-900 mb-2 text-center">
            {autoGenProgress ? '코스를 만들고 있어요' : '준비 중이에요'}
          </h2>

          {/* 진행 상황 메시지 */}
          <p className="text-sm font-bold text-gray-500 mb-6 text-center h-5 transition-all duration-500">
            {autoGenProgress?.message || '잠시만 기다려 주세요...'}
          </p>

          {/* 프로그레스 바 */}
          <div className="w-full max-w-[280px] space-y-2">
            <div className="w-full h-2 bg-gray-100 rounded-full overflow-hidden">
              <div
                className="h-full bg-gradient-to-r from-[#0066FF] to-[#4D9AFF] rounded-full transition-all duration-700 ease-out"
                style={{ width: `${autoGenProgress?.progress || 3}%` }}
              />
            </div>
            <div className="flex justify-between text-[11px] font-bold text-gray-300">
              <span>분석</span>
              <span>검색</span>
              <span>평가</span>
              <span>생성</span>
            </div>
          </div>

          {/* 단계 표시 */}
          {autoGenProgress && (
            <div className="mt-8 flex items-center gap-2 px-4 py-2 bg-blue-50 rounded-full">
              <div className="w-1.5 h-1.5 bg-[#0066FF] rounded-full animate-pulse" />
              <span className="text-xs font-bold text-[#0066FF]">{autoGenProgress.progress}% 완료</span>
            </div>
          )}
        </div>
      )}

      <div
        ref={mapRef}
        id="map_div"
        className="absolute inset-0 z-0 bg-[#E5E7EB]"
        style={{ height: "100vh" }}
      />

      {/* 3개 코스 선택 버튼 (우측 상단) - Updated Layout */}
      {allCourses.length > 1 && viewMode === 'course' && (
        <div className="absolute top-48 right-4 z-[100] flex flex-col gap-2.5 items-end animate-fade-in-right">
          {allCourses.map((course, idx) => (
            <button
              key={course.course_id}
              onClick={() => handleCourseSelect(idx)}
              className={`px-4 py-3 rounded-2xl font-bold text-xs shadow-lg transition-all flex items-center gap-2.5 ${selectedCourseIndex === idx
                ? 'bg-[#0066FF] text-white scale-105 ring-4 ring-blue-500/20 shadow-blue-500/30'
                : 'bg-white text-gray-600 hover:bg-gray-50 border border-gray-100'
                }`}
            >
              <span className={`flex items-center justify-center w-5 h-5 rounded-full text-[10px] font-black ${selectedCourseIndex === idx ? 'bg-white/20 text-white' : 'bg-gray-100 text-gray-500'}`}>
                {idx + 1}
              </span>
              <span className="truncate max-w-[120px]">{course.course_name}</span>
            </button>
          ))}
        </div>
      )}

      <header className="absolute top-0 left-0 right-0 z-50 bg-white shadow-sm flex flex-col pointer-events-auto">
        <div className="flex items-center px-6 py-4">
          <h1 className="text-xl font-black text-gray-900 flex items-center gap-2">
            <span className="text-[#0066FF]">📍</span> 내주변
          </h1>
        </div>

        <div className="flex border-b">
          <button
            onClick={() => { setViewMode('places'); setTimeout(searchPlaces, 100); }}
            className={`flex-1 py-3 text-sm font-black transition-all ${viewMode === 'places' ? 'text-[#0066FF] border-b-2 border-[#0066FF]' : 'text-gray-400'}`}
          >
            장소
          </button>
          <button
            onClick={() => setViewMode('course')}
            className={`flex-1 py-3 text-sm font-black transition-all ${viewMode === 'course' ? 'text-[#0066FF] border-b-2 border-[#0066FF]' : 'text-gray-400'}`}
          >
            코스
          </button>
        </div>

        {/* 검색 바 추가 */}
        <div className="px-6 pt-4 pb-2 bg-white">
          <form onSubmit={handleKeywordSearch} className="relative shadow-sm rounded-xl">
            <input
              type="text"
              value={searchKeyword}
              onChange={(e) => setSearchKeyword(e.target.value)}
              placeholder="장소, 주소 검색 (예: 동명동 맛집)"
              className="w-full pl-10 pr-12 py-3.5 bg-gray-50 border border-gray-100 rounded-xl text-sm font-bold text-gray-900 focus:outline-none focus:ring-2 focus:ring-[#0066FF] focus:bg-white transition-all placeholder:text-gray-400"
            />
            <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
            {searchKeyword && (
              <button
                type="button"
                onClick={() => setSearchKeyword('')}
                className="absolute right-3 top-1/2 -translate-y-1/2 p-1 text-gray-300 hover:text-gray-500"
              >
                <X size={16} fill="currentColor" className="opacity-50" />
              </button>
            )}
          </form>
        </div>

        {viewMode === 'places' && (
          <div className="px-6 py-2 pb-4 flex gap-2 overflow-x-auto no-scrollbar bg-white">
            {['전체', '맛집', '카페', '관광'].map((cat) => (
              <button
                key={cat}
                onClick={() => {
                  setActiveCategory(cat);
                  setViewMode('places'); // 카테고리 클릭 시 장소 모드로 전환
                  setAllPlaces([]); // 이전 결과 즉시 삭제 (화면 초기화)
                  // 상태 업데이트 후 검색은 useEffect 또는 즉시 호출 고민 -> 여기서는 검색 트리거를 위해 의존성 활용
                  setTimeout(searchPlaces, 100);
                }}
                className={`px-5 py-2 rounded-full text-xs font-black whitespace-nowrap transition-all shadow-sm ${activeCategory === cat
                  ? 'bg-[#0066FF] text-white'
                  : 'bg-white text-gray-600 border border-gray-100'
                  }`}
              >
                {cat === '맛집' ? '🍴 ' : cat === '카페' ? '☕ ' : cat === '관광' ? '🎡 ' : 'ALL '}
                {cat}
              </button>
            ))}
          </div>
        )}
      </header>

      {isSearching && !isAutoGenerating && (
        <div className="fixed inset-0 z-[9999] flex items-center justify-center pointer-events-none">
          <div className="bg-white/90 backdrop-blur-md px-6 py-4 rounded-2xl shadow-xl flex flex-col items-center gap-3 border border-gray-100 animate-fade-in">
            <div className="w-8 h-8 border-4 border-[#0066FF] border-t-transparent rounded-full animate-spin"></div>
            <span className="text-xs font-bold text-gray-600">장소를 찾고 있어요...</span>
          </div>
        </div>
      )}

      <div className="absolute top-[180px] left-1/2 -translate-x-1/2 z-40">
        {viewMode === 'places' && (
          <button
            onClick={searchPlaces}
            className="bg-white/90 backdrop-blur-md px-6 py-2.5 rounded-full shadow-2xl border border-white/50 text-[#0066FF] font-black text-sm flex items-center gap-2 active:scale-95 transition-all">
            <span className="animate-spin-slow text-lg">🔄</span>
            현 지도에서 검색
          </button>
        )}
      </div>

      {/* AI 수정 버튼 (코스 모드 좌측 상단) */}
      {viewMode === 'course' && allCourses.length > 0 && (
        <div className="absolute top-[180px] left-4 z-40">
          <button
            onClick={() => setIsRefineOpen(true)}
            className="bg-[#0066FF] text-white px-4 py-2.5 rounded-full shadow-lg flex items-center gap-2 active:scale-95 transition-all font-black text-sm border-2 border-white/50"
          >
            <Edit3 size={14} />
            AI 수정
          </button>
        </div>
      )}

      {/* 내 위치 버튼 */}
      <div className="absolute bottom-48 right-5 z-40">
        <button
          onClick={() => {
            if (!navigator.geolocation) {
              alert("위치 정보를 사용할 수 없습니다.");
              return;
            }
            setIsSearching(true);
            navigator.geolocation.getCurrentPosition((position) => {
              const { latitude, longitude } = position.coords;
              if (mapInstance.current && (window as any).Tmapv3) {
                const Tmapv3 = (window as any).Tmapv3;
                const newCenter = new Tmapv3.LatLng(latitude, longitude);
                mapInstance.current.setCenter(newCenter);

                // 내 위치 표시 마커 (파란 점)
                new Tmapv3.Marker({
                  position: newCenter,
                  map: mapInstance.current,
                  iconHTML: `<div style="width:20px; height:20px; background:#0066FF; border:3px solid white; border-radius:50%; box-shadow:0 4px 8px rgba(0,0,0,0.2);"></div>`
                });
              }
              setIsSearching(false);
            }, () => {
              alert("위치 정보를 가져올 수 없습니다.");
              setIsSearching(false);
            });
          }}
          className="w-12 h-12 bg-white rounded-full shadow-lg flex items-center justify-center text-gray-700 active:bg-gray-50 active:scale-95 transition-all"
        >
          <Locate size={24} />
        </button>
      </div>

      {/* [Refine Agent] 수정 패널 (바텀시트 위에 오버레이) */}
      {isRefineOpen && viewMode === 'course' && (
        <div className="absolute left-0 right-0 top-0 z-[300] animate-fade-in">
          {/* 배경 오버레이 */}
          <div className="fixed inset-0 bg-black/20" onClick={() => { setIsRefineOpen(false); setRefineMessage(null); }} />

          {/* 패널 */}
          <div className="relative bg-white rounded-b-3xl shadow-[0_10px_40px_rgba(0,0,0,0.15)] p-5 pb-5">
            {/* 헤더 */}
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-full bg-[#0066FF] flex items-center justify-center">
                  <Edit3 size={14} className="text-white" />
                </div>
                <div>
                  <span className="text-sm font-black text-gray-900">AI 코스 수정</span>
                  <p className="text-[10px] text-gray-400 font-bold">장소 교체, 추가, 위치 변경 등</p>
                </div>
              </div>
              <button onClick={() => { setIsRefineOpen(false); setRefineMessage(null); }} className="w-8 h-8 rounded-full bg-gray-100 flex items-center justify-center">
                <X size={16} className="text-gray-500" />
              </button>
            </div>

            {/* AI 응답 */}
            {refineMessage && (
              <div className="mb-3 px-4 py-3 bg-blue-50 rounded-2xl">
                <span className="text-xs font-bold text-[#0066FF]">{refineMessage}</span>
              </div>
            )}

            {/* 빠른 액션 칩 */}
            <div className="flex gap-2 mb-3 overflow-x-auto hide-scrollbar">
              {["1번째 바꿔줘", "카페 추가", "더 가까운 곳으로", "분위기 좋은 곳"].map((chip) => (
                <button
                  key={chip}
                  onClick={() => { setRefineInput(chip); }}
                  className="px-3 py-1.5 bg-gray-50 border border-gray-100 rounded-full text-[11px] font-bold text-gray-500 whitespace-nowrap active:bg-blue-50 active:text-[#0066FF] active:border-blue-200 transition-colors"
                >
                  {chip}
                </button>
              ))}
            </div>

            {/* 입력 바 */}
            <div className="flex items-center gap-2 bg-gray-50 rounded-2xl px-4 py-3 border border-gray-100">
              <input
                value={refineInput}
                onChange={e => setRefineInput(e.target.value)}
                onKeyPress={e => e.key === 'Enter' && handleRefine()}
                placeholder="수정 요청을 입력하세요..."
                className="flex-1 bg-transparent outline-none text-sm font-bold text-gray-700 placeholder:text-gray-300"
                disabled={isRefining}
                autoFocus
              />
              <button
                onClick={handleRefine}
                disabled={!refineInput.trim() || isRefining}
                className={`w-10 h-10 rounded-full flex items-center justify-center shrink-0 transition-all ${
                  refineInput.trim() && !isRefining
                    ? 'bg-[#0066FF] text-white shadow-lg active:scale-90'
                    : 'bg-gray-200 text-gray-400'
                }`}
              >
                {isRefining ? (
                  <Loader2 size={16} className="animate-spin" />
                ) : (
                  <Send size={16} />
                )}
              </button>
            </div>
          </div>
        </div>
      )}

      <MotionDiv
        drag="y"
        dragConstraints={{ top: 0, bottom: 0 }}
        dragElastic={0.1}
        onDragEnd={handleDragEnd}
        animate={controls}
        initial={{ height: OPEN_HEIGHT }}
        className="absolute bottom-0 left-0 right-0 bg-white shadow-[0_-20px_50px_rgba(0,0,0,0.1)] rounded-t-[3rem] z-[200] overflow-hidden"
      >
        <div className="w-full pt-4 pb-2 cursor-grab active:cursor-grabbing flex justify-center touch-none">
          <div className="w-16 h-1.5 bg-gray-200 rounded-full" />
        </div>

        {spots.length === 0 && !selectedPlace && !isDetailLoading ? (
          <div className="p-8 text-center text-gray-400 font-bold">
            코스 정보가 없습니다.<br />채팅에서 여행 코스를 생성해주세요.
          </div>
        ) : (
          <div className="px-8 flex flex-col h-full overflow-hidden">
            {/* 1. Detail View Mode */}
            {(selectedPlace || isDetailLoading) ? (
              <div className="animate-fade-in space-y-4 pt-2 h-full flex flex-col">
                {/* Header with Back Button */}
                <div className="flex items-center justify-between">
                  <button
                    onClick={() => {
                      if (abortControllerRef.current) {
                        abortControllerRef.current.abort();
                        abortControllerRef.current = null;
                      }
                      setSelectedPlace(null);
                      setIsDetailLoading(false);
                    }}
                    className="flex items-center gap-1 text-gray-500 hover:text-gray-900 transition-colors"
                  >
                    <ArrowLeft size={20} />
                    <span className="text-sm font-bold">목록으로</span>
                  </button>
                  <span className="text-xs font-bold text-[#0066FF] bg-blue-50 px-3 py-1 rounded-full">AI 장소 분석</span>
                </div>

                {/* Title */}
                <h3 className="text-2xl font-black text-gray-900 border-b border-gray-100 pb-3">
                  {selectedPlace?.name || "장소 정보 검색 중..."}
                </h3>

                {/* Loading State */}
                {isDetailLoading ? (
                  <div className="flex flex-col items-center justify-center py-10 gap-4">
                    <div className="w-10 h-10 border-4 border-[#0066FF] border-t-transparent rounded-full animate-spin"></div>
                    <p className="text-sm text-gray-500 font-medium animate-pulse">
                      AI 에이전트가 정보를 찾고 있어요...
                    </p>
                  </div>
                ) : (
                  /* Content State */
                  <div className="flex-1 overflow-y-auto custom-scrollbar pb-20">
                    {selectedPlace?.img && (
                      <div className="relative w-full h-48 rounded-2xl overflow-hidden mb-5 shadow-sm bg-gray-100">
                        <img
                          src={selectedPlace.img}
                          alt={selectedPlace.name}
                          className="w-full h-full object-cover animate-fade-in"
                          loading="lazy"
                          onError={(e) => {
                            (e.target as HTMLImageElement).parentElement!.style.display = 'none';
                          }}
                        />
                      </div>
                    )}

                    <div className="bg-gray-50 p-5 rounded-2xl text-sm text-gray-700 leading-relaxed whitespace-pre-line border border-gray-100 font-medium shadow-sm">
                      {selectedPlace?.content}
                    </div>

                    <div className="mt-4 flex gap-3">
                      <button
                        onClick={addToCourse}
                        className="flex-1 py-4 bg-white border-2 border-[#0066FF] text-[#0066FF] font-black rounded-xl active:scale-95 transition-all flex items-center justify-center gap-2 hover:bg-blue-50"
                      >
                        <span className="text-lg">+</span> 코스에 추가
                      </button>
                      <button
                        onClick={() => {
                          setSelectedPlace(null);
                          setIsDetailLoading(false);
                        }}
                        className="flex-1 py-4 bg-[#0066FF] text-white font-bold rounded-xl active:scale-95 transition-all shadow-lg shadow-blue-100"
                      >
                        닫기
                      </button>
                    </div>
                  </div>
                )}
              </div>
            ) : !sheetOpen && viewMode === 'course' ? (
              // 2. Collapsed Course View
              <div className="flex items-center justify-between py-4 animate-fade-in">
                <div className="flex-1">
                  <span className="text-[10px] font-black text-[#0066FF] uppercase tracking-widest mb-1 block">최적 경로 분석 완료</span>
                  <h2 className="text-xl font-black text-gray-900 tracking-tight">
                    {activeStep + 1}. {spots[activeStep].name}
                  </h2>
                  <span className="text-gray-300 font-bold text-sm">다음 장소까지 {spots[activeStep].transport}</span>
                </div>
                <button
                  onClick={() => {
                    setSheetOpen(true);
                    setIsCourseDetailExpanded(false);
                  }}
                  className="w-14 h-14 bg-[#0066FF] text-white rounded-2xl flex items-center justify-center shadow-lg shadow-blue-100 active:scale-95 transition-all"
                >
                  <Navigation2 size={24} fill="currentColor" />
                </button>
              </div>
            ) : viewMode === 'course' ? (
              isCourseDetailExpanded ? (
                // [2-B] Expanded Detail View (상세 길찾기 및 정보)
                <div className="animate-fade-in space-y-6 pt-2 h-full flex flex-col overflow-y-auto pb-48 custom-scrollbar">
                  {/* Back Header */}
                  <div className="flex items-center justify-between border-b border-gray-50 pb-4 shrink-0">
                    <div className="flex items-center gap-3">
                      <button
                        onClick={() => setIsCourseDetailExpanded(false)}
                        className="w-10 h-10 bg-gray-50 rounded-full flex items-center justify-center hover:bg-gray-100 active:scale-95 transition-all text-gray-600"
                      >
                        <ArrowLeft size={20} />
                      </button>
                      <div>
                        <h3 className="text-lg font-black text-gray-900">코스 상세 정보</h3>
                        <p className="text-xs text-gray-400 font-medium">{activeStep + 1}번째 장소 탐색 중</p>
                      </div>
                    </div>
                    <button
                      onClick={() => {
                        setIsCourseDetailExpanded(false);
                        setIsEditMode(true);
                      }}
                      className="px-3 py-2 bg-gray-100 text-gray-600 rounded-lg text-xs font-bold hover:bg-gray-200 transition-all flex items-center gap-1.5"
                    >
                      <Edit3 size={14} />
                      편집
                    </button>
                  </div>

                  <div className="space-y-3 shrink-0">
                    <div className="flex justify-between items-center">
                      <span className="text-sm font-black text-gray-900 tracking-tight">단계 {activeStep + 1} / {spots.length}</span>
                      <span className="text-[10px] font-bold text-[#0066FF] bg-blue-50 px-3 py-1 rounded-full">Tmap 실시간 데이터</span>
                    </div>
                    <div className="w-full h-1.5 bg-gray-100 rounded-full overflow-hidden">
                      <div className="h-full bg-[#0066FF] transition-all duration-700" style={{ width: `${((activeStep + 1) / spots.length) * 100}%` }} />
                    </div>
                  </div>

                  <div className="flex gap-4 items-start shrink-0">
                    <div className="w-24 h-24 rounded-2xl overflow-hidden shadow-md shrink-0 border border-gray-100 bg-gray-50">
                      {spots[activeStep].img ? (
                        <img
                          src={spots[activeStep].img}
                          className="w-full h-full object-cover animate-fade-in"
                          alt="place"
                          loading="lazy"
                          onError={(e) => {
                            const img = e.target as HTMLImageElement;
                            img.style.display = 'none';
                            if (img.parentElement) {
                              img.parentElement.innerText = '📍';
                            }
                          }}
                        />
                      ) : (
                        <div className="w-full h-full flex items-center justify-center text-3xl">📍</div>
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <h3 className="text-lg font-black text-gray-900 mb-2 break-words">{spots[activeStep].name}</h3>
                      <p className="text-xs font-bold text-gray-500 leading-relaxed mb-3 line-clamp-3">{spots[activeStep].desc}</p>
                      <div className="flex flex-wrap gap-1.5">
                        {Array.isArray(spots[activeStep].tags) && spots[activeStep].tags.map((t: string) => (
                          <span key={t} className="px-2 py-1 bg-gray-50 rounded-md text-[10px] font-black text-gray-400">{t}</span>
                        ))}
                      </div>
                    </div>
                  </div>

                  {/* [추억 남기기] 버튼 - 확정된 코스에서만 표시 */}
                  {allCourses[selectedCourseIndex]?.is_selected && (() => {
                    const currentSpot = spots[activeStep];
                    const memorySpots = JSON.parse(localStorage.getItem('memory_spots') || '[]');
                    const isAdded = memorySpots.some((s: any) => s.name === currentSpot?.name);

                    return (
                      <button
                        onClick={() => {
                          const memorySpots = JSON.parse(localStorage.getItem('memory_spots') || '[]');
                          const alreadyAdded = memorySpots.some((s: any) => s.name === currentSpot.name);

                          if (alreadyAdded) {
                            // 제거
                            const updated = memorySpots.filter((s: any) => s.name !== currentSpot.name);
                            localStorage.setItem('memory_spots', JSON.stringify(updated));
                            setToastMessage('추억에서 제거했습니다');
                          } else {
                            // 추가
                            memorySpots.push(currentSpot);
                            localStorage.setItem('memory_spots', JSON.stringify(memorySpots));
                            setToastMessage(`${currentSpot.name}을(를) 추억에 남겼습니다! 📸`);
                          }
                          // 강제 리렌더링을 위해 상태 업데이트
                          setActiveStep(activeStep);
                        }}
                        className={`w-full py-3 rounded-2xl font-black text-sm shadow-lg active:scale-95 transition-all flex items-center justify-center gap-2 ${isAdded
                          ? 'bg-gradient-to-r from-green-500 to-emerald-500 text-white shadow-green-200'
                          : 'bg-gradient-to-r from-pink-500 to-purple-500 text-white shadow-pink-200'
                          }`}
                      >
                        <span className="text-lg">{isAdded ? '✅' : '📸'}</span>
                        {isAdded ? '추억에 저장됨' : '추억 남기기'}
                      </button>
                    );
                  })()}

                  <div className="flex gap-3 shrink-0">
                    <button onClick={prevStep} disabled={activeStep === 0} className="flex-1 py-4 bg-gray-50 text-gray-400 rounded-2xl font-black text-sm disabled:opacity-30 active:scale-95 transition-all">이전</button>
                    {allCourses[selectedCourseIndex]?.is_selected && activeStep === spots.length - 1 ? (
                      <button
                        onClick={async () => {
                          const userId = localStorage.getItem('temp_user_id');
                          const memorySpots = JSON.parse(localStorage.getItem('memory_spots') || '[]');
                          const currentCourseMeta = JSON.parse(localStorage.getItem('current_course_meta') || '{}');

                          console.log('🎉 여행 마무리 버튼 클릭!');
                          console.log('userId:', userId);
                          console.log('memorySpots:', memorySpots);
                          console.log('currentCourseMeta:', currentCourseMeta);
                          console.log('course_id:', currentCourseMeta.course_id);

                          // 타임라인 생성
                          if (currentCourseMeta.course_id && memorySpots.length > 0) {
                            try {
                              const API_URL = (process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api').replace(/\/api\/?$/, '');
                              console.log('API 호출 시작:', `${API_URL}/api/journey/${currentCourseMeta.course_id}/create-timeline`);

                              const response = await fetch(`${API_URL}/api/journey/${currentCourseMeta.course_id}/create-timeline`, {
                                method: 'POST',
                                headers: { 'Content-Type': 'application/json' },
                                body: JSON.stringify({
                                  userId: userId,
                                  memorySpots: memorySpots,
                                  tastingNotes: {}
                                })
                              });

                              console.log('HTTP 상태:', response.status, response.statusText);

                              let result;
                              try {
                                result = await response.json();
                                console.log('API 응답:', result);
                              } catch (jsonError) {
                                const text = await response.text();
                                console.error('JSON 파싱 실패, 응답 텍스트:', text);
                                result = { error: text };
                              }

                              if (response.ok) {
                                setToastMessage('타임라인이 생성되었습니다! 📸');
                                // 타임라인 생성 성공 후 추억 장소 초기화
                                localStorage.removeItem('memory_spots');
                                console.log('✅ memory_spots 초기화 완료');
                              } else {
                                console.error('API 에러:', result);
                                setToastMessage(`타임라인 생성 실패: ${response.status}`);
                              }
                            } catch (e) {
                              console.error("Failed to create timeline", e);
                              setToastMessage('타임라인 생성 중 오류 발생');
                            }
                          } else {
                            console.warn('타임라인 생성 조건 미충족:');
                            console.warn('- course_id 존재:', !!currentCourseMeta.course_id);
                            console.warn('- memory_spots 개수:', memorySpots.length);

                            if (!currentCourseMeta.course_id) {
                              setToastMessage('코스 정보를 찾을 수 없습니다');
                            } else if (memorySpots.length === 0) {
                              setToastMessage('추억 남긴 장소가 없습니다. 📸 버튼을 눌러주세요!');
                            }
                          }

                          // 테이스팅 노트로 이동
                          router.push('/tasting-note');
                        }}
                        className="flex-1 py-4 bg-gradient-to-r from-blue-500 to-indigo-600 text-white rounded-2xl font-black text-sm active:scale-95 transition-all shadow-lg shadow-blue-200 flex items-center justify-center gap-2"
                      >
                        <span className="text-lg">🎉</span> 여행 마무리
                      </button>
                    ) : (
                      <button onClick={nextStep} disabled={activeStep === spots.length - 1} className="flex-1 py-4 bg-gray-100 text-gray-800 rounded-2xl font-black text-sm disabled:opacity-30 active:scale-95 transition-all">다음 장소</button>
                    )}
                  </div>

                  <div className="flex flex-col gap-2 mt-2 shrink-0">
                    <div className="flex gap-2">
                      <button
                        onClick={() => {
                          fetchRoute('pedestrian');
                          setSheetOpen(false);
                        }}
                        disabled={isLoadingRoute || activeStep >= spots.length - 1}
                        className={`flex-1 py-3 rounded-2xl font-black text-sm transition-all flex flex-col items-center justify-center gap-1 shadow-sm border active:scale-95 ${routeMode === 'pedestrian'
                          ? 'bg-[#0066FF] text-white border-[#0066FF]'
                          : 'bg-white text-gray-700 border-gray-200'
                          }`}
                      >
                        <span className="flex items-center gap-1.5"><span className="text-lg">🚶</span> 도보 안내</span>
                        {totalTime > 0 && routeMode === 'pedestrian' && <span className="text-[10px] opacity-90 font-bold">{formatTime(totalTime)}</span>}
                      </button>

                      <button
                        onClick={() => {
                          fetchRoute('car');
                          setSheetOpen(false);
                        }}
                        disabled={isLoadingRoute || activeStep >= spots.length - 1}
                        className={`flex-1 py-3 rounded-2xl font-black text-sm transition-all flex flex-col items-center justify-center gap-1 shadow-sm border active:scale-95 ${routeMode === 'car'
                          ? 'bg-[#00C853] text-white border-[#00C853]'
                          : 'bg-white text-gray-700 border-gray-200'
                          }`}
                      >
                        <span className="flex items-center gap-1.5"><span className="text-lg">🚗</span> 차량 안내</span>
                        {totalTime > 0 && routeMode === 'car' && (
                          <span className="text-[10px] opacity-90 font-bold flex flex-col items-center leading-tight">
                            <span>{formatTime(totalTime)}</span>
                            {totalFare > 0 && <span>{totalFare.toLocaleString()}원</span>}
                          </span>
                        )}
                      </button>
                    </div>

                    <div className="bg-gray-50 rounded-2xl border border-gray-100 px-3 py-2.5 flex flex-row items-center gap-3">
                      <span className="text-xs font-black text-gray-800 shrink-0">길찾기</span>
                      <div className="flex gap-2">
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            const dest = spots[activeStep];
                            const url = `https://map.naver.com/v5/directions/-/${dest.lng},${dest.lat},${encodeURIComponent(dest.name)}/-/car`;
                            window.open(url, '_blank');
                          }}
                          className="w-9 h-9 bg-white rounded-lg shadow-sm border border-gray-100 flex items-center justify-center hover:scale-105 transition-transform"
                        >
                          <span className="text-[#03C75A] font-black text-[10px]">N</span>
                        </button>
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            const dest = spots[activeStep];
                            const destName = encodeURIComponent(dest.name.replace(/,/g, ' '));
                            const url = `https://map.kakao.com/link/to/${destName},${dest.lat},${dest.lng}`;
                            window.open(url, '_blank');
                          }}
                          className="w-9 h-9 bg-[#FEE500] rounded-lg shadow-sm border border-gray-100 flex items-center justify-center hover:scale-105 transition-transform"
                        >
                          <span className="text-[#1952C5] font-black text-[10px]">K</span>
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              ) : (
                // [2-A] Summary View (Horizontal Scroll List)
                <div className="flex flex-col h-full pb-6 pt-2 relative">
                  {/* 코스 헤더 (2줄 구조 - 모바일 최적화) */}
                  <div className="mb-4 shrink-0">
                    {/* 1줄: 코스 이름 */}
                    <div className="flex items-center gap-2 mb-1">
                      <span className="bg-[#0066FF] text-white text-[10px] px-2 py-0.5 rounded-sm font-bold shrink-0">Recommended</span>
                      <h2 className="text-lg font-bold text-gray-900 truncate">{allCourses[selectedCourseIndex]?.course_name || "광주 핫플레이스 코스"}</h2>
                    </div>

                    {/* 설명 */}
                    <p className="text-sm text-gray-500 font-medium line-clamp-1 mb-2">
                      {allCourses[selectedCourseIndex]?.course_description || '광주 맞춤 코스'}
                      {totalTime > 0 && ` · ${formatTime(totalTime)}`}
                      {totalFare > 0 && ` · ${totalFare.toLocaleString()}원`}
                      {isLoadingRoute && ' · 경로 계산 중...'}
                    </p>

                    {/* 2줄: 액션 버튼 (겹치지 않게 flex-wrap) */}
                    <div className="flex items-center gap-2 flex-wrap">
                      <button
                        onClick={() => setIsEditMode(!isEditMode)}
                        className={`h-9 px-3 rounded-full flex items-center justify-center gap-1 transition-all shadow-sm border font-bold text-[11px] ${isEditMode ? 'bg-gray-800 border-gray-800 text-white' : 'bg-white border-gray-200 text-gray-600'}`}
                      >
                        {isEditMode ? <Check size={14} /> : <Edit3 size={14} />}
                        <span>{isEditMode ? '완료' : '편집'}</span>
                      </button>

                      <button
                        onClick={() => setIsCourseDetailExpanded(true)}
                        className="h-9 px-3 bg-gray-100 text-gray-600 rounded-full flex items-center justify-center transition-all active:scale-95 text-[11px] font-bold gap-1"
                      >
                        <Navigation2 size={12} />
                        <span>길찾기</span>
                      </button>
                    </div>

                    {/* 태그 */}
                    <div className="flex gap-2 mt-2 flex-wrap">
                      <span className="text-xs border border-pink-200 text-pink-500 bg-pink-50 px-2 py-1 rounded-md font-bold">연인과</span>
                      <span className="text-xs border border-pink-200 text-pink-500 bg-pink-50 px-2 py-1 rounded-md font-bold">데이트</span>
                      <span className="text-xs border border-blue-200 text-blue-500 bg-blue-50 px-2 py-1 rounded-md font-bold">힐링</span>
                    </div>
                  </div>

                  {isEditMode ? (
                    /* Edit Mode - Vertical Sortable List */
                    <div className="flex-1 overflow-y-auto custom-scrollbar pb-4 -mx-6 px-6">
                      <ReorderGroup axis="y" values={spots} onReorder={handleReorder} className="space-y-2">
                        {spots.map((spot, index) => (
                          <ReorderItem
                            key={spot.id}
                            value={spot}
                            className="relative select-none"
                          >
                            <div className="flex items-center gap-3 p-3 bg-white border border-gray-200 rounded-xl shadow-sm active:shadow-md transition-shadow">
                              <div className="text-gray-400 cursor-grab active:cursor-grabbing p-2 touch-none">
                                <GripVertical size={20} />
                              </div>

                              <div className="flex-1 min-w-0 pointer-events-none">
                                <div className="flex items-center gap-2">
                                  <span className="bg-gray-100 text-gray-600 text-[10px] px-1.5 py-0.5 rounded font-bold">
                                    #{index + 1}
                                  </span>
                                  <h3 className="font-bold text-gray-900 truncate text-sm">
                                    {spot.name}
                                  </h3>
                                </div>
                                <p className="text-xs text-gray-500 truncate mt-0.5">
                                  {spot.address || spot.category}
                                </p>
                              </div>

                              <button
                                onClick={(e) => handleDeleteSpot(index, e)}
                                onPointerDown={(e) => e.stopPropagation()}
                                className="text-red-400 p-2 bg-red-50 rounded-lg hover:bg-red-100 active:scale-95 transition-all pointer-events-auto"
                              >
                                <Trash2 size={16} />
                              </button>
                            </div>
                          </ReorderItem>
                        ))}
                      </ReorderGroup>
                      <div className="text-center text-xs text-gray-400 mt-4 font-medium animate-pulse">
                        💡 순서를 드래그하여 변경하거나 장소를 삭제하세요.
                      </div>
                    </div>
                  ) : (
                    /* View Mode - Horizontal List */
                    <div className="flex overflow-x-auto gap-3 pb-4 -mx-6 px-6 snap-x no-scrollbar">
                      {spots.map((spot, index) => (
                        <div
                          key={index}
                          onClick={() => {
                            setActiveStep(index);
                            setIsCourseDetailExpanded(true); // [MODIFIED] 카드 클릭 시 상세(길찾기) 뷰로 전환
                            // 클릭 시 지도 이동
                            if (mapInstance.current && (window as any).Tmapv3) {
                              const Tmapv3 = (window as any).Tmapv3;
                              mapInstance.current.panTo(new Tmapv3.LatLng(spot.lat, spot.lng));
                            }
                          }}
                          className={`snap-center shrink-0 w-[280px] p-3 rounded-xl border bg-white flex gap-3 cursor-pointer transition-all active:scale-95 ${activeStep === index ? 'border-[#0066FF] ring-1 ring-[#0066FF] shadow-md' : 'border-gray-200 shadow-sm'}`}
                        >
                          <div className="relative w-20 h-20 bg-gray-100 rounded-lg overflow-hidden shrink-0">
                            <span className="absolute top-0 left-0 bg-black/70 text-white text-xs px-2 py-1 rounded-br-lg font-bold z-10">{index + 1}</span>
                            {spot.img ? (
                              <img
                                src={spot.img}
                                className="w-full h-full object-cover transition-opacity duration-300 opacity-0"
                                loading="lazy"
                                onLoad={(e) => (e.target as HTMLImageElement).style.opacity = '1'}
                                onError={(e) => {
                                  const img = e.target as HTMLImageElement;
                                  img.style.display = 'none';
                                  if (img.parentElement) {
                                    img.parentElement.innerHTML = '<div class="w-full h-full flex items-center justify-center text-2xl bg-gray-50">📍</div>';
                                  }
                                }}
                              />
                            ) : (
                              <div className="w-full h-full flex items-center justify-center text-2xl bg-gray-50">📍</div>
                            )}
                          </div>
                          <div className="flex flex-col justify-center min-w-0 flex-1">
                            <h3 className="font-bold text-gray-900 truncate text-base">{spot.name}</h3>
                            <div className="text-xs text-gray-500 truncate mt-0.5">{spot.address || spot.category}</div>
                            <div className="flex items-center gap-1 mt-2 text-xs text-gray-400 font-medium">
                              <span className="text-yellow-400">★</span> <span>4.5</span>
                            </div>
                          </div>

                          {/* [+ 담기] 버튼: 확정되지 않은 코스에서만 표시 */}
                          {!allCourses[selectedCourseIndex]?.is_selected && (
                            <div className="flex flex-col gap-1 items-center justify-center pl-2 border-l border-gray-100">
                              <button
                                onClick={(e) => togglePickSpot(e, spot)}
                                className={`w-10 h-10 rounded-full flex items-center justify-center transition-all ${pickedSpots.some(p => p.name === spot.name)
                                  ? 'bg-[#0066FF] text-white shadow-md shadow-blue-200 scale-110'
                                  : 'bg-gray-100 text-gray-400 hover:bg-gray-200'
                                  }`}
                              >
                                {(() => {
                                  const idx = pickedSpots.findIndex(p => p.name === spot.name);
                                  return idx !== -1 ? <span className="text-sm font-black">{idx + 1}</span> : <span className="text-lg font-bold">+</span>;
                                })()}
                              </button>
                              <span className="text-[9px] font-bold text-gray-400">
                                {pickedSpots.some(p => p.name === spot.name) ? '담김' : '담기'}
                              </span>
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  )}

                  <div className="mt-4 flex flex-col gap-3 pb-6">
                    {allCourses[selectedCourseIndex]?.is_selected ? (
                      <button
                        disabled
                        className="w-full bg-[#00C853] text-white font-bold py-3.5 rounded-xl shadow-lg shadow-green-100 cursor-default flex items-center justify-center gap-2"
                      >
                        <span className="text-lg">🏕️</span> 이 코스로 여행 중입니다
                      </button>
                    ) : (
                      <button
                        onClick={handleConfirmCourse}
                        className="w-full bg-[#0066FF] text-white font-bold py-3.5 rounded-xl shadow-lg shadow-blue-100 active:scale-95 transition-transform flex items-center justify-center gap-2"
                      >
                        <span className="text-lg">✅</span> 이 코스로 결정하기
                      </button>
                    )}
                  </div>
                </div>
              )
            ) : (
              // 3. Places Mode (Vertical List)
              <div className="flex-1 overflow-y-auto custom-scrollbar pb-20 pt-2">
                <div className="space-y-3">
                  {(allPlaces.length > 0 ? allPlaces : []).map((spot, index) => (
                    <div key={index} className="flex gap-4 p-3 border border-gray-100 rounded-xl bg-white shadow-sm hover:shadow-md transition-all cursor-pointer"
                      onClick={() => {
                        if (mapInstance.current && (window as any).Tmapv3) {
                          const Tmapv3 = (window as any).Tmapv3;
                          mapInstance.current.setCenter(new Tmapv3.LatLng(spot.lat, spot.lng));
                          mapInstance.current.setZoom(17);
                        }
                      }}>
                      <div className="w-16 h-16 bg-gray-100 rounded-lg flex items-center justify-center text-2xl shrink-0">
                        {spot.category === '맛집' ? '🍴' : spot.category === '카페' ? '☕' : '📍'}
                      </div>
                      <div className="flex-1 min-w-0">
                        <h4 className="font-bold text-gray-900">{spot.name}</h4>
                        <p className="text-xs text-gray-500 mt-1 truncate">{spot.address}</p>
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            fetchPlaceDetail(spot.name, spot.address);
                          }}
                          className="mt-2 text-xs bg-[#0066FF] text-white px-3 py-1 rounded-full font-bold">
                          상세보기
                        </button>
                      </div>
                    </div>
                  ))}
                  {allPlaces.length === 0 && !isSearching && (
                    <div className="text-center py-10 text-gray-400 text-sm">
                      검색 결과가 없습니다.
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        )}
      </MotionDiv>

      <div className="fixed bottom-0 left-0 right-0 h-24 bg-white z-[150]" />
      <LoginInducementModal
        isOpen={showLoginModal}
        onClose={() => setShowLoginModal(false)}
        featureName={modalFeature}
      />

    </div >
  );
};
